#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "cc -D_DARWIN_C_SOURCE -UOPENSSL_BN_ASM_PART_WORDS -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -Wno-unused-value -Wno-parentheses"
  #define PLATFORM "darwin-i386-cc"
  #define DATE "Tue Nov  3 17:16:06 CST 2015"
#endif
